const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

// Define the 'Country' model
const Country = sequelize.define('Country', {
  // id — auto-generated by Sequelize
  id: {
    type: DataTypes.INTEGER,
    autoIncrement: true,
    primaryKey: true
  },
  // name — required
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true // We'll make sure each country name is unique
  },
  // capital — optional
  capital: {
    type: DataTypes.STRING,
    allowNull: true
  },
  // region — optional
  region: {
    type: DataTypes.STRING,
    allowNull: true
  },
  // population — required
  population: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  // currency_code — required
  currency_code: {
    type: DataTypes.STRING,
    allowNull: true // Set to true to allow nulls as per instructions
  },
  // exchange_rate — required
  exchange_rate: {
    type: DataTypes.FLOAT, // Use FLOAT for decimal values
    allowNull: true // Set to true to allow nulls as per instructions
  },
  // estimated_gdp — computed
  estimated_gdp: {
    type: DataTypes.FLOAT, // Use FLOAT for decimal values
    allowNull: true // Can be null or 0 as per instructions
  },
  // flag_url — optional
  flag_url: {
    type: DataTypes.STRING(512), // Give it a bit more length
    allowNull: true
  }
  // last_refreshed_at — auto timestamp
  // Sequelize handles this automatically
}, {
  // Model options
  timestamps: true, // This enables createdAt and updatedAt
  createdAt: false, // We don't need 'createdAt'
  updatedAt: 'last_refreshed_at' // We rename 'updatedAt' to 'last_refreshed_at'
});

module.exports = Country;